In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
data1 = np.loadtxt("broken2.txt") # broken gear
data2 = np.loadtxt("faulty.txt")  # faulty gear
data3 = np.loadtxt("healthy.txt")  # healthy gear
data4 = np.loadtxt('misaligned.txt') # misaligned Gear
#data5 = np.loadtxt("balls.txt") # balls
#data6 = np.loadtxt("file.txt")  # dont know yet we will see
#data7 = np.loadtxt("inner.txt")  # inner bearing
#data8 = np.loadtxt("healthy_bearing.txt") # healthy bearing

In [ ]:
df1 = pd.DataFrame(data1,columns=["bg1","bg2","bg3","bg4"])
df2 = pd.DataFrame(data2,columns=["fg1","fg2","fg3","fg4"])
df3 = pd.DataFrame(data3,columns=["hg1","hg2","hg3","hg4"])
df4 = pd.DataFrame(data4,columns=["mg1","mg2","mg3","mg4"])
#df5 = pd.DataFrame(data5,columns=["bl1","bl2","bl3","bl4"])
#df6 = pd.DataFrame(data6,columns=["fl1","fl2","fl3","fl4"])
#df7 = pd.DataFrame(data7,columns=['in1','in2','in3','in4'])
#df8 = pd.DataFrame(data8,columns=["hb1","hb2","hb3","hb4"])




In [ ]:
from sklearn.decomposition import PCA
pca = PCA(n_components=1)


In [ ]:
df1_new = pca.fit_transform(df1[["bg2","bg3","bg4"]])

In [ ]:
df1_new = pd.DataFrame(df1_new,columns=["Displacement"])
df1_new["time"] = df1["bg1"]

In [ ]:
df1_new = df1_new[["time","Displacement"]]
df1_new.describe()

time  Displacement
count  1437.000000  1.437000e+03
mean      4.939307  1.215191e-12
std       2.884910  4.487073e+04
min       0.000000 -2.157023e+05
25%       2.480000 -3.028751e+04
50%       4.920000 -4.914035e+02
75%       7.385398  2.903636e+04
max      10.000000  2.379197e+05

In [ ]:
df2_new = pca.fit_transform(df2[["fg2","fg3","fg4"]])

In [ ]:
df2_new = pd.DataFrame(df2_new,columns=["Displacement"])
df2_new["time"] = df2[["fg1"]]
df2_new = df2_new[["time","Displacement"]]
df2_new.describe()


time  Displacement
count  40035.000000  4.003500e+04
mean     400.047912  8.945012e-17
std      230.961387  1.338310e+01
min        0.000000 -1.507206e+02
25%      200.050000 -3.936927e+00
50%      400.120000  2.396669e-03
75%      600.030000  3.886492e+00
max      800.000000  1.530584e+02

In [ ]:
df3_new = pca.fit_transform(df3[["hg2","hg3","hg4"]])
df3_new = pd.DataFrame(df3_new,columns=["Displacement"])
df3_new["time"] = df3[["hg1"]]
df3_new = df3_new[["time","Displacement"]]
df3_new.describe()


time  Displacement
count  40009.000000  4.000900e+04
mean     400.011927  1.669400e-17
std      230.958137  3.271251e+00
min        0.000000 -4.124766e+01
25%      200.000000 -2.433797e+00
50%      400.040000 -3.948363e-02
75%      600.020000  2.386945e+00
max      800.000000  4.263459e+01

In [ ]:
df4_new = pca.fit_transform(df4[["mg2","mg3","mg4"]])
df4_new = pd.DataFrame(df4_new,columns=["Displacement"])
df4_new["time"] = df4[["mg1"]]
df4_new = df4_new[["time","Displacement"]]
df4_new.describe()


time  Displacement
count  40780.000000  4.078000e+04
mean     400.844294 -1.903551e-17
std      231.042409  2.374389e+00
min        0.000000 -3.394473e+00
25%      200.455000 -2.376917e+00
50%      402.090000  9.909368e-04
75%      600.685000  2.373459e+00
max      800.000000  7.151515e+00

In [ ]:
# prompt: Divide the df1_new into 20 different dataframes with sequentially

import numpy as np
df1_splits = np.array_split(df1_new, 40)

# Access each split dataframe using its index:
df1_split_1 = df1_splits[0]
df1_split_2 = df1_splits[1]
# ... and so on


In [ ]:
import pandas as pd
d1 = df1_splits[0].describe().loc[["count","mean","std","min","max"]]
d1_summary = pd.DataFrame(d1.T,columns=["count","mean","std","min","max"])
for i in range(1,40):
  d = df1_splits[i].describe().loc[["count",'mean',"std","min","max"]]
  d_summary = pd.DataFrame(d.T,columns=["count","mean","std","min","max"])
  d1_summary = pd.concat([d1_summary,d_summary],axis= 0)

d1_summary

count          mean           std            min            max
time           36.0      0.089509      0.059830       0.000000       0.200000
Displacement   36.0  17288.890794  56920.220445  -91588.912570  237919.653126
time           36.0      0.318285      0.067868       0.212050       0.435702
Displacement   36.0   2347.184113  46647.840814  -86365.907024  122411.715814
time           36.0      0.557583      0.071719       0.440000       0.680000
...             ...           ...           ...            ...            ...
Displacement   35.0  -4393.550097  40285.636058  -80499.122768   87674.731877
time           35.0      9.605344      0.075614       9.480000       9.739820
Displacement   35.0   1324.664043  50758.862673 -103716.982949  143584.598218
time           35.0      9.883032      0.070402       9.740000      10.000000
Displacement   35.0  10395.725257  37597.256800  -76100.465067   76484.934752

[80 rows x 5 columns]

In [ ]:
# prompt: Delete the row time in d1_summary

d1_summary = d1_summary.drop(index="time")
d1_summary['Target'] = 0



In [ ]:
# prompt: drop the count colum in the d1_summary

d1_summary = d1_summary.drop(columns=["count"])


In [ ]:
d1_summary.shape

(40, 5)

In [ ]:
df2_splits = np.array_split(df2_new, 100)


In [ ]:
import pandas as pd
d2 = df2_splits[0].describe().loc[["count","mean","std","min","max"]]
d2_summary = pd.DataFrame(d2.T,columns=["count","mean","std","min","max"])
for i in range(1,100):
  d = df2_splits[i].describe().loc[["count",'mean',"std","min","max"]]
  d_summary = pd.DataFrame(d.T,columns=["count","mean","std","min","max"])
  d2_summary = pd.concat([d2_summary,d_summary],axis= 0)



In [ ]:
d2_summary['Target'] = 1
d2_summary = d2_summary.drop(columns=['count'])
d2_summary

mean        std         min         max  Target
time            3.959746   2.316303    0.000000    7.940000       1
Displacement   -0.033802   5.861373  -23.947385   33.132219       1
time           11.960000   2.318060    7.960000   15.960000       1
Displacement    0.161078   8.535456  -26.782106   46.171638       1
time           19.963342   2.313240   15.980000   23.960000       1
...                  ...        ...         ...         ...     ...
Displacement   -0.115696  17.952512 -109.954517  115.430354       1
time          788.037900   2.298056  784.060000  792.000000       1
Displacement   -0.147717  15.110680  -74.305321   57.340816       1
time          796.010000   2.312286  792.020000  800.000000       1
Displacement    0.103951  11.258705  -37.737258   50.900241       1

[200 rows x 5 columns]

In [ ]:
d2_summary.shape

(200, 5)

In [ ]:
d2_summary = d2_summary.drop(index='time')


In [ ]:
d2_summary.shape

(100, 5)

In [ ]:
df3_splits = np.array_split(df3_new, 100)

In [ ]:

import pandas as pd
d3 = df3_splits[0].describe().loc[["count","mean","std","min","max"]]
d3_summary = pd.DataFrame(d3.T,columns=["count","mean","std","min","max"])
for i in range(1,100):
  d = df3_splits[i].describe().loc[["count",'mean',"std","min","max"]]
  d_summary = pd.DataFrame(d.T,columns=["count","mean","std","min","max"])
  d3_summary = pd.concat([d3_summary,d_summary],axis= 0)

d3_summary

count        mean       std         min         max
time          401.0    3.980050  2.317973    0.000000    7.980000
Displacement  401.0   -0.034563  2.367852   -5.424689    3.384314
time          401.0   12.000000  2.318060    8.000000   16.000000
Displacement  401.0    0.040551  2.854253  -21.484647   16.460432
time          401.0   20.020000  2.318060   16.020000   24.020000
...             ...         ...       ...         ...         ...
Displacement  400.0    0.045975  3.220945  -12.587845   17.231500
time          400.0  788.010000  2.312286  784.020000  792.000000
Displacement  400.0    0.059026  3.197026  -26.390131   24.410086
time          400.0  796.010000  2.312286  792.020000  800.000000
Displacement  400.0   -0.062127  2.387429  -20.098789   24.711560

[200 rows x 5 columns]

In [ ]:
d3_summary['Target'] = 2
d3_summary = d3_summary.drop(columns=['count'])
d3_summary = d3_summary.drop(index='time')
d3_summary

mean       std        min        max  Target
Displacement -0.034563  2.367852  -5.424689   3.384314       2
Displacement  0.040551  2.854253 -21.484647  16.460432       2
Displacement -0.016176  2.375432  -3.416789   3.400400       2
Displacement  0.014937  2.440217  -6.017737   9.249637       2
Displacement -0.039932  2.375192  -3.416789   3.400707       2
...                ...       ...        ...        ...     ...
Displacement  0.071562  2.379811  -3.395307   3.387654       2
Displacement -0.090012  4.780391 -24.738289  27.430244       2
Displacement  0.045975  3.220945 -12.587845  17.231500       2
Displacement  0.059026  3.197026 -26.390131  24.410086       2
Displacement -0.062127  2.387429 -20.098789  24.711560       2

[100 rows x 5 columns]

In [ ]:
d3_summary['Target'] = 2

In [ ]:
df4_splits = np.array_split(df4_new, 100)

In [ ]:
# df4_splits = np.array_split(df4_new, 40)
import pandas as pd
d4 = df4_splits[0].describe().loc[["count","mean","std","min","max"]]
d4_summary = pd.DataFrame(d4.T,columns=["count","mean","std","min","max"])
for i in range(1,100):
  d = df4_splits[i].describe().loc[["count",'mean',"std","min","max"]]
  d_summary = pd.DataFrame(d.T,columns=["count","mean","std","min","max"])
  d4_summary = pd.concat([d4_summary,d_summary],axis= 0)

d4_summary

count        mean       std         min         max
time          408.0    3.892425  2.265166    0.000000    7.780000
Displacement  408.0    0.025811  2.408201   -3.376763    7.151515
time          408.0   11.740392  2.285540    7.800000   15.680000
Displacement  408.0    0.066373  2.392388   -3.377779    3.379923
time          408.0   19.603039  2.261326   15.700000   23.520000
...             ...         ...       ...         ...         ...
Displacement  407.0   -0.000857  2.372326   -3.380239    3.377665
time          407.0  787.944079  2.295832  784.000000  791.940000
Displacement  407.0    0.044844  2.390427   -3.382009    3.373478
time          407.0  796.002604  2.342225  791.960000  800.000000
Displacement  407.0   -0.088785  2.373575   -3.359645    3.355640

[200 rows x 5 columns]

In [ ]:
d4_summary['Target'] = 3
d4_summary = d4_summary.drop(columns=['count'])
d4_summary = d4_summary.drop(index='time')
d4_summary

mean       std       min       max  Target
Displacement  0.025811  2.408201 -3.376763  7.151515       3
Displacement  0.066373  2.392388 -3.377779  3.379923       3
Displacement  0.024888  2.357399 -3.384362  3.378292       3
Displacement -0.013283  2.375125 -3.380212  3.378217       3
Displacement -0.001849  2.380310 -3.377360  3.375206       3
...                ...       ...       ...       ...     ...
Displacement -0.007038  2.387809 -3.358552  3.355345       3
Displacement -0.014440  2.360953 -3.381794  3.379418       3
Displacement -0.000857  2.372326 -3.380239  3.377665       3
Displacement  0.044844  2.390427 -3.382009  3.373478       3
Displacement -0.088785  2.373575 -3.359645  3.355640       3

[100 rows x 5 columns]

In [ ]:
df_final = pd.concat([d1_summary,d2_summary,d3_summary,d4_summary],axis=0)
df_final.shape

(340, 5)

In [ ]:
df_final

mean           std            min            max  Target
Displacement  17288.890794  56920.220445  -91588.912570  237919.653126       0
Displacement   2347.184113  46647.840814  -86365.907024  122411.715814       0
Displacement   2984.224319  48686.613625 -119028.636808   94896.026077       0
Displacement   5580.925801  37973.448780  -69349.302840   93834.616508       0
Displacement    547.301848  46967.757018  -82263.482267   96802.889744       0
...                    ...           ...            ...            ...     ...
Displacement     -0.007038      2.387809      -3.358552       3.355345       3
Displacement     -0.014440      2.360953      -3.381794       3.379418       3
Displacement     -0.000857      2.372326      -3.380239       3.377665       3
Displacement      0.044844      2.390427      -3.382009       3.373478       3
Displacement     -0.088785      2.373575      -3.359645       3.355640       3

[340 rows x 5 columns]

In [ ]:
df_final

mean           std            min            max  Target
Displacement  17288.890794  56920.220445  -91588.912570  237919.653126       0
Displacement   2347.184113  46647.840814  -86365.907024  122411.715814       0
Displacement   2984.224319  48686.613625 -119028.636808   94896.026077       0
Displacement   5580.925801  37973.448780  -69349.302840   93834.616508       0
Displacement    547.301848  46967.757018  -82263.482267   96802.889744       0
...                    ...           ...            ...            ...     ...
Displacement     -0.007038      2.387809      -3.358552       3.355345       3
Displacement     -0.014440      2.360953      -3.381794       3.379418       3
Displacement     -0.000857      2.372326      -3.380239       3.377665       3
Displacement      0.044844      2.390427      -3.382009       3.373478       3
Displacement     -0.088785      2.373575      -3.359645       3.355640       3

[340 rows x 5 columns]

In [ ]:
X = df_final.iloc[:,0:4].values
Y = df_final.iloc[:,-1].values

In [ ]:
from sklearn.model_selection import  train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.3,random_state=20)

In [ ]:
# from sklearn.preprocessing import StandardScaler
# scaler = StandardScaler()

# x_train = scaler.fit_transform(x_train)
# x_test = scaler.transform(x_test)

In [ ]:
from sklearn.linear_model import LogisticRegression

#set Regularization rate
reg = 0.1

# train a logistic regession model on training set

multi_model = LogisticRegression(C = 1/reg, solver='lbfgs',multi_class ='auto',max_iter = 100000,verbose=1)
multi_model.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=2):
ABNORMAL_TERMINATION_IN_LNSRCH.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(C=10.0, max_iter=100000, verbose=1)

In [ ]:
y_pred = multi_model.predict(x_test)

In [ ]:
print('Predicted_label :', y_pred[15:30])
print('Actual_label: ', y_test[15:30])

Predicted_label : [1 1 0 1 1 0 0 1 1 0 1 0 1 0 0]
Actual_label:  [2 1 3 2 2 2 3 2 1 3 2 3 1 0 3]


In [ ]:
from sklearn.metrics import classification_report

print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.92      0.27      0.41        45
           1       0.97      0.52      0.67        56
           2       0.00      0.00      0.00         1
           3       0.00      0.00      0.00         0

    accuracy                           0.40       102
   macro avg       0.47      0.20      0.27       102
weighted avg       0.94      0.40      0.55       102



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

In [ ]:
# prompt: count each unique values in the y_test

import numpy as np
unique, counts = np.unique(y_test, return_counts=True)
print(np.asarray((unique, counts)).T)


[[ 0 13]
 [ 1 30]
 [ 2 34]
 [ 3 25]]


In [ ]:
print('accuracy_score:',accuracy_score(y_pred,y_test))

accuracy_score: 0.4019607843137255


In [ ]:
cf = confusion_matrix(y_pred,y_test)
print(cf)

[[12  1  7 25]
 [ 0 29 27  0]
 [ 1  0  0  0]
 [ 0  0  0  0]]


In [ ]:
from sklearn.tree import DecisionTreeClassifier
dtree_model = DecisionTreeClassifier(max_depth = 4)
dtree_model.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=4)

In [ ]:
dtree_pred = dtree_model.predict(x_test)

In [ ]:
# create confusion matrix
dcm = confusion_matrix(y_test,dtree_pred)
dcm

array([[13,  0,  0,  0],
       [ 0, 27,  3,  0],
       [ 0,  4, 29,  1],
       [ 0,  0,  0, 25]])

In [ ]:
print("accuracy of decision_tree is :",accuracy_score(y_test,dtree_pred))

accuracy of decision_tree is : 0.9215686274509803


**Classification using SVM**

In [ ]:
from sklearn.svm import SVC
svm_model_linear = SVC(kernel = 'linear', C=1)
svm_model_linear.fit(x_train,y_train)

SVC(C=1, kernel='linear')

In [ ]:
svm_linear_pred = svm_model_linear.predict(x_test)

In [ ]:
# creating confusion matrix
slcm = confusion_matrix(y_test,svm_linear_pred)
slcm

array([[13,  0,  0,  0],
       [ 0, 26,  3,  1],
       [ 0,  0, 27,  7],
       [ 0,  0,  1, 24]])

In [ ]:
print("accuracy of the linear SVM model is :", accuracy_score(y_test,svm_linear_pred))

accuracy of the linear SVM model is : 0.8823529411764706


WHen training with the SVM Radial Basis Function, two parameters are considered **'C'** and **'Gamma'**
A low **C** makes the decision surface smooth, while high **C** aims at classifying all the training examples correctly.
**gamma** defines how much influence s single training example has. The larger **gamma** is, closer other examples must be affected.
Use GridSeardCV fo fing optimal **C** and **gamma**

In [ ]:
from sklearn.svm import SVC
svm_model_rbf = SVC(kernel ='rbf', C=1,class_weight='balanced')
svm_model_rbf.fit(x_train,y_train)

SVC(C=1, class_weight='balanced')

In [ ]:
svm_rbf_pred = svm_model_linear.predict(x_test)

In [ ]:
# creating confusion matrix
srcm = confusion_matrix(y_test,svm_linear_pred)
srcm

array([[13,  0,  0,  0],
       [ 0, 26,  3,  1],
       [ 0,  0, 27,  7],
       [ 0,  0,  1, 24]])

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier

In [ ]:
clf1 = LogisticRegression(C=1/0.1,solver='lbfgs',multi_class ='auto',max_iter=10000)
clf2 = SVC(kernel ='linear', C=1)
clf3 = DecisionTreeClassifier(max_depth = 4)


In [ ]:
estimators = [('lr',clf1),('svm',clf2),('DT',clf3)]

In [ ]:
from sklearn.model_selection import cross_val_score

In [ ]:
for estimator in estimators:
  x = cross_val_score(estimator[1],X,Y,cv=10,scoring='accuracy')
  print(estimator[0],np.round(np.mean(x),2))

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=2):
ABNORMAL_TERMINATION_IN_LNSRCH.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=2):
ABNORMAL_TERMINATION_IN_LNSRCH.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr

lr 0.59
svm 0.88
DT 0.93


In [ ]:
print(
    "The best parameters are %s with a score of %0.2f"
    % (grid.best_params_, grid.best_score_)
)

NameError: name 'grid' is not defined

In [ ]:
print("accuracy of the linear SVM model is :", accuracy_score(y_test,svm_rbf_pred))

**KNN classifier**

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(x_train,y_train)

In [ ]:
kpred = knn.predict(x_test)

In [ ]:
# confusuon matrix for KNN
kcm = confusion_matrix(y_test,kpred)
kcm

In [ ]:
print("accuracy of the KNN is :",accuracy_score(y_test,kpred))

In [ ]:
# prompt: Apply fft to df1 to column Displacement and plot it where x-axis values will be frequency and Y-axis values will be Displacement values

import numpy as np
import matplotlib.pyplot as plt

fft_values = np.fft.fft(df1_new["Displacement"])
plt.plot(np.abs(fft_values))
plt.xlabel("Frequency")
plt.ylabel("Displacement")
plt.show()
print("fft_values",fft_values.shape)
ft1 = pd.DataFrame(fft_values,columns=["Data"])
ft1.head()


In [ ]:
# prompt: Generate the same in above cell for the df2
# _new

import matplotlib.pyplot as plt
import numpy as np
fft_values = np.fft.fft(df2_new["Displacement"])
plt.plot(np.abs(fft_values))
plt.xlabel("Frequency")
plt.ylabel("Displacement")
plt.show()


In [ ]:
# prompt: Generate the same for df3_new

import matplotlib.pyplot as plt
import numpy as np
fft_values = np.fft.fft(df3_new["Displacement"])
plt.plot(np.abs(fft_values))
plt.xlabel("Frequency")
plt.ylabel("Displacement")
plt.show()
print("fft_values",fft_values)


In [ ]:
# prompt: Generate the same for  df4_new

import matplotlib.pyplot as plt
import numpy as np
fft_values = np.fft.fft(df4_new["Displacement"])
plt.plot(np.abs(fft_values))
plt.xlabel("Frequency")
plt.ylabel("Displacement")
plt.show()


In [ ]:
df1_new = df1[["bg2","bg3","bg4"]].copy()
df2_new = df2[["fg2","fg3","fg4"]].copy()
df3_new = df3[["hg2","hg3","hg4"]].copy()
df4_new = df4[["mg2","mg3","mg4"]].copy()


In [ ]:
df1_transform = pca.fit_transform(df1_new[['bg3',"bg4"]])
df1_transform = pd.DataFrame(df1_transform,columns=["Data"])
df1_transform["target"] = 0

In [ ]:
df2_transform = pca.fit_transform(df2_new)
df2_transform = pd.DataFrame(df2_transform,columns=["data"])
df2_transform["target"] = 1


In [ ]:
df3_transform = pca.fit_transform(df3_new)
df3_transform = pd.DataFrame(df3_transform,columns=["Data"])
df3_transform["target"] = 2

In [ ]:
df4_transform = pca.fit_transform(df4_new)
df4_transform = pd.DataFrame(df4_transform,columns=["Data"])
df4_transform["target"] = 3


In [ ]:
gear_data = pd.concat([df1_transform,df1_transform,df3_transform,df4_transform],axis=0)

In [ ]:
gear_data.head()

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X = gear_data.iloc[:,0]
y = gear_data.iloc[:,-1]

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [ ]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(multi_class='multinomial')

In [ ]:
# prompt: reshape the x_train, y_train to be able to train clf which is logistic regression

import numpy as np
x_train = np.array(x_train).reshape(-1,1)
y_train = np.array(y_train).reshape(-1,1)


In [ ]:
clf.fit(x_train,y_train)

In [ ]:
x_test = np.array(x_test).reshape(-1,1)
y_test = np.array(y_test).reshape(-1,1)

In [ ]:
y_pred = clf.predict(x_test)


In [ ]:
from sklearn.metrics import r2_score

In [ ]:
# prompt: Generate the fft of df2 and plot it

import matplotlib.pyplot as plt
import numpy as np
fft_values_df2 = np.fft.fft(df2[''])

plt.plot(fft_values_df2)
plt.xlabel('Frequency')
plt.ylabel('Magnitude')
plt.title('FFT of Broken Data')
plt.show()


In [ ]:
# prompt: Generate the ffit of df6 and plot it

import matplotlib.pyplot as plt
import numpy as np
fft_values_df6 = np.fft.fft(df6)

plt.plot(fft_values_df6)
plt.xlabel('Frequency')
plt.ylabel('Magnitude')
plt.title('FFT of Misaligned Data')
plt.show()


In [ ]:
# prompt: Generate a fft of df1 and plot it

import matplotlib.pyplot as plt
import numpy as np
fft_values_df1 = np.fft.fft(df1)

plt.plot(fft_values_df1)
plt.xlabel('Frequency')
plt.ylabel('Magnitude')
plt.title('FFT of Balls Data')
plt.show()


In [ ]:
# prompt: Sample the frequency plot of the df5 and plot it as keep sampling frequency moderate

import matplotlib.pyplot as plt
import numpy as np
fft_values_df5 = np.fft.fft(df5)

plt.plot(fft_values_df5[:len(fft_values_df5)//2])
plt.xlabel('Frequency')
plt.ylabel('Magnitude')
plt.title('FFT of Healthy Data (Sampled)')
plt.show()


In [ ]:
fs = 5
# sampling frequency
fmax = 25
# sampling period
dt = 1/fs
# length of signal
N  = 75

df = fmax/N
f = np.arange(0,N)*df

xf = np.fft.fft(First_2000.mm)*dt